stages:
  - install
  - test
  - build
  - deploy

variables:
#  NODE_ENV: 'production'
  CI: 'true'
  VITE_BASE_URL:

cache:
  paths:
    - node_modules/

install:
  stage: install
  image: node:18
  script:
    - npm install

test:
  stage: test
  image: node:18
  script:
    - npm run type-check

build:
  stage: build
  image: node:18
  script:
    - npm run build
  artifacts:
    paths:
      - dist/
  only:
    - main
#
#deploy:
#  stage: deploy
#  image: alpine
#  script:
#    - echo "Deploy step can be configured for your hosting service"
#  environment:
#    name: production
#    url: https://example.com  # Replace with your production URL
#  only:
#    - main
